config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard" => "accounts#index"

  resources :posts, only: [:new,:create,:show]
  
  root to: "public#homepage"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :posts

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    0
  end


  def total_following
    0
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :account

    before_create :set_active

    scope :active, -> { where active: true}

    def set_active
        self.active = true
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_account, only: [:profile]

    def index
        # user dashboard - post feed
        @posts = Post.active
    end

    def profile
       # user profile
       @posts =@account.posts.active
    end

    def set_account
        @account = Account.find_by_username(params[:username])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :image, :image_cache, :description, :website])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password])

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.account_id =current_account.id if account_signed_in?

        if @post.save
            redirect_to dashboard_path, flash: { success: "Post was created successfully!" }
        else
            redirect_to new_post_path, flash: { danger: "Post was not saved!" }
        end
    end

    def show
    end

    private

    def post_params
        params.require(:post).permit(:image, :image_cache)
    end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def homepage
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-8">
            <% @posts.each do |post| %>
                <div class="insta-post">
                    <div class="post-meta">
                        <%= post.account.username %>
                    </div>

                    <%= image_tag post.image.url, class: "img img-fluid" %>
                </div>
            <% end %>
        </div>
        <div class="col-4">
            <div class="account-summary">
                <p><strong><%= current_account.username %></strong><br />
                <%= current_account.full_name %></p>
            </div>
            <div class="follower-suggestions">
            </div>
        </div>
    </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <%= image_tag @account.image.url, width: "200px",  class: "profile-pic"%>
        </div>
        <div class="col-8 text-left">
            <h1><%= @account.full_name %></h1>
            <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-secondary"%>
            <div class="profile-stats"><%= @account.posts.count %> posts</div>
            <div class="profile-stats"><%= @account.total_followers %> followers</div>
            <div class="profile-stats"><%= @account.total_following %> following</div>

            <p><%= @account.full_name%></p>
            <%= simple_format @account.description %>
            <p><%= link_to @account.website if @account.website.present? %></p>
        </div>
    </div>
    <div class="row profile-posts">
        <% @posts.each do |post| %>
                <div class="col-4">
                    <div class="insta-post">
                        <%= image_tag post.image.url, class: "img img-fluid" %>
                    </div>
                </div>
        <% end %>
    </div>
</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item active">
    <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "New Post", new_post_path, class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/_public_nav.html.erb
<li class="nav-item active">
    <a class="nav-link" href="/">Home
        <span class="sr-only">(current)</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="#">About</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="#">Services</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="#">Contact</a>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  
  <title>Instagram Clone</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="/">Instagram Clone</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if account_signed_in? %>
            <%= render "layouts/account_nav" %>
          <% else %>
            <%= render "layouts/public_nav" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= yield %>    
      </div>
    </div>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

<%= f.file_field :image, class: "form-control" %>
<%= f.hidden_field :image_cache %>

<%= f.submit "Save Post", class: "btn btn-success" %>

<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render "form" %>